name: SPASE cron test

on: workflow_call

jobs:
  # This workflow contains a single job called "validate"
  notify:
    name: Notify that a push has occurred
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Send mail
        # Define the following secrets for the repository: EMAIL_SERVER, EMAIL_USERNAME, EMAIL_PASSWORD, EMAIL_TO, EMAIL_LIST
        if: always()
        uses: dawidd6/action-send-mail@v2
        with:
          # mail server settings
          server_address: ${{ secrets.EMAIL_SERVER }}
          server_port: 465
          # user credentials
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          # email subject
          subject: ${{ steps.date.outputs.date }} ${{ github.repository }} cron test
          # email body as text
          body: test!!
          # comma-separated string, send email to
          to: ${{ secrets.TESTING_EMAIL_LIST }},${{ secrets.EMAIL_TO }}
          # from email name
          from: HPDE Mailer
